name: iOS Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Install xcpretty
        run: sudo gem install xcpretty --no-document

      - name: List available simulators (debug)
        run: xcrun simctl list devices

      - name: Build and test (unit + UI)
        run: |
          set -euo pipefail
          xcodebuild \
            -scheme Gomoku \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -derivedDataPath DerivedData \
            test | tee xcodebuild.log | xcpretty

      - name: Archive test logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: DerivedData-Logs
          path: |
            DerivedData/Logs
            xcodebuild.log
